### ISSUE TITLE
Where is External Tools?

### ISSUE THREAD

**Issue by EvelinaBiserova** [ugeneunipro/ugeneunipro.github.io#14]
[ugene.net/download-all_html](http://ugene.net/download-all_html) contains External Tools section, but new version [ugeneunipro.github.io/download-all.html](https://ugeneunipro.github.io/download-all.html) doesn't contain it

**Comment by EvelinaBiserova** [comment]
Also check "Old UGENE Packages" section of [old page](http://ugene.net/download-all_html). "external tools" link is http://ugene.net/external.html which is the same as http://ugene.net/download-all.html#en_data_analysis_tools, which links to External tools which are missing

**Comment by yalgaer** [comment]
We will reduce amount of distributions we have and externals tools will not be anymore a separate distrubution.
There are multiple reasons for that

1) Our portable packages includes all external tools. We have no portable package with no external tools

2) Our online installer package expects that a user installs a correct version of external tools through the installer: no need in external package.

3) The tools from UGENE.v1 are not tested/will work with UGENE.v2. So we always include them into the package to avoid mix-and-match errors on the user side

4) We are not a vendor of external tools to distribute them standalone: our external tools are not the original tools but a stripped version of them. For example blast+ does not include a lot of blast utilities that UGENE can't use. Same for other tools.
