### ISSUE TITLE
The "News" page doesn't have pictures

### ISSUE THREAD

**Issue by DmitriiSukhomlinov** [ugeneunipro/ugeneunipro.github.io#2]
There are several pictures should be on [the "News" page](https://ugeneunipro.github.io/news.html), but they are absent in the new version.
![old](https://user-images.githubusercontent.com/26257527/113814581-13559400-979c-11eb-8366-85113cdc80b0.png)
![new](https://user-images.githubusercontent.com/26257527/113814608-1c466580-979c-11eb-97c8-c8c6244dad90.png)

**Comment by yalgaer** [comment]
Added all pictures. Please check.

**Comment by yalgaer** [comment]
Fixed
