### ISSUE TITLE
Can't download data from the "Podcasts" page

### ISSUE THREAD

**Issue by DmitriiSukhomlinov** [ugeneunipro/ugeneunipro.github.io#3]
Go to [the "Podcasts" page](https://ugeneunipro.github.io/podcast.html), find "Download a zip-archive with an example BAM file and the reference sequence" (the bottom of the page) and try to download - it doesn't work.

**Comment by yalgaer** [comment]
The problem should be fixed. Please re-check.

**Comment by yalgaer** [comment]
Closing as fixed. Please re-open if the problem still exists

**Comment by EvelinaBiserova** [comment]
Works. You can close issue
