### ISSUE TITLE
Wrong link on Metagenomic page

### ISSUE THREAD

**Issue by EvelinaBiserova** [ugeneunipro/ugeneunipro.github.io#41]
[Metagenomic Classification with Kraken](https://ugeneunipro.github.io/metagenomic-classification-with-kraken/) page, the "Download the UGENE" links should link to the [Download UGENE](https://ugeneunipro.github.io/download.html) page.

**Comment by EvelinaBiserova** [comment]
Please, on the same page, replace the link with the text "Build Kraken Database" with https://doc.ugene.net/wiki/display/UM38/Build+Kraken+Database+Element

**Comment by yalgaer** [comment]
Fixed.
