### ISSUE TITLE
Why does the Russian page contain information about external tools, but the English one does not?

### ISSUE THREAD

**Issue by EvelinaBiserova** [ugeneunipro/ugeneunipro.github.io#42]
Compare https://ugeneunipro.github.io/download-all.html and https://ugeneunipro.github.io/ru/download-all.html. The Russian version has an "Внешние инструменты" section, but the English version does not have the "External Tools".

**Comment by yalgaer** [comment]
Fixed

**Comment by EvelinaBiserova** [comment]
@yalgaer, where can the user find a package of external tools for the current version of UGENE?
