### ISSUE TITLE
Add URI fragment to External Tools link

### ISSUE THREAD

**Issue by EvelinaBiserova** [ugeneunipro/ugeneunipro.github.io#43]
[Download UGENE and components page](https://ugeneunipro.github.io/download-all.html), link inside text "external tools (including tools for NGS data analysis)". I want a link https://ugeneunipro.github.io/download-all.html#external_tools instead of https://ugeneunipro.github.io/download-all.html

**Comment by EvelinaBiserova** [comment]
Or you can do as on [the Russian page](https://ugeneunipro.github.io/ru/download-all.html): insert a link to [the documentation](https://doc.ugene.net/wiki/display/UM38/Data+Analysis+Tools).

**Comment by yalgaer** [comment]
Done
