### ISSUE TITLE
No need to open links in a new tab

### ISSUE THREAD

**Issue by EvelinaBiserova** [ugeneunipro/ugeneunipro.github.io#44]
After [that commit](https://github.com/ugeneunipro/ugeneunipro.github.io/commit/1a66eff5a0af0a89b03502a6440ff80b9ed3516d) some links open in a new tab and some don't. For example

- Documentation->UGENE Key Features openes in the same tab,
- but Documentation->YouTube Podcast in new tab.

**Comment by yalgaer** [comment]
All external links (docs/youtube/forum) should be opened in new tabs.

Please reopen this bug if there are external links with no target="_black" with 1 bug per page, so the result is trackable.

**Comment by EvelinaBiserova** [comment]
> Please reopen this bug if there are external links with no target="_black" with 1 bug per page, so the result is trackable.

I don't understand.

**Comment by EvelinaBiserova** [comment]
[changelist](http://ugene.net/changelist.html), all "here" links.

**Comment by EvelinaBiserova** [comment]
[support](http://ugene.net/support.html#ask_question), "our forum".

**Comment by EvelinaBiserova** [comment]
[support](http://ugene.net/support.html#free_bug_fix), "forum".

**Comment by EvelinaBiserova** [comment]
[support](http://ugene.net/support.html#free_bug_fix), "our bug-tracking system".

**Comment by EvelinaBiserova** [comment]
[support](http://ugene.net/support.html#free_bug_fix), "here".

**Comment by EvelinaBiserova** [comment]
[support](http://ugene.net/support.html#free_new_feature), "forum".

**Comment by EvelinaBiserova** [comment]
[support](http://ugene.net/support.html#free_new_feature), "bug-tracking system".

**Comment by EvelinaBiserova** [comment]
[key_features](http://ugene.net/key_features.html), "Cloning in silico".

**Comment by yalgaer** [comment]
Fixed the links from your list.

**Comment by EvelinaBiserova** [comment]
@yalgaer, oh, I'm sorry, but it looks like the links from this list **should** open in a new tab. It seems that I accidentally got confused and confused everyone.

Do I understand correctly that the documentation, the bug tracker should open in a new tab?

**Comment by EvelinaBiserova** [comment]
So, I finally figured it out. All perfectly.
