### ISSUE TITLE
Add current_version.html

### ISSUE THREAD

**Issue by EvelinaBiserova** [ugeneunipro/ugeneunipro.github.io#49]
I do not know why this is so, but my 36th offline package gives an error on startup.
![image](https://user-images.githubusercontent.com/39720063/117261405-4b72f400-ae7a-11eb-9056-92474a208e94.png)

**Comment by yalgaer** [comment]
The patch is submitted. Please check

**Comment by EvelinaBiserova** [comment]
Yes, everything works, thanks
