### ISSUE TITLE
ugene.net: wrong redirect to Jira

### ISSUE THREAD

**Issue by EvelinaBiserova** [ugeneunipro/ugeneunipro.github.io#5]
[ugeneunipro.github.io](https://ugeneunipro.github.io/)
![image](https://user-images.githubusercontent.com/39720063/114383010-4098ac80-9bb7-11eb-9682-73014860c6df.png)

[ugene.net](http://ugene.net/)
![image](https://user-images.githubusercontent.com/39720063/114383199-7a69b300-9bb7-11eb-8de5-ce643212ada4.png)

**Comment by yalgaer** [comment]
The correct domain for our tracker is ugene.dev, not ugene.unipro.ru. 
The ugene.unipro.ru is the old one.
