### ISSUE TITLE
The old forum link is invalid

### ISSUE THREAD

**Issue by DmitriiSukhomlinov** [ugeneunipro/ugeneunipro.github.io#55]
https://ugene.unipro.ru/forum/ is the old forum link, it should has a redirection to the new one https://forum.ugene.net/forum/

**Comment by EvelinaBiserova** [comment]
@DmitriiSukhomlinov, can I close this pull request?

**Comment by DmitriiSukhomlinov** [comment]
> @DmitriiSukhomlinov, can I close this pull request?

No, this problem hasn't been fixed yet

**Comment by EvelinaBiserova** [comment]
> > @DmitriiSukhomlinov, can I close this pull request?
> 
> No, this problem hasn't been fixed yet

As far as I know, this repository cannot modify the ugene.unipro.ru site.

**Comment by yalgaer** [comment]
This should be done via a permanent HTTP redirect by the admin of the ugene.unipro.ru site. I have no admin rights to this site.
Closing this issue. 
Please re-open if it is related to the ugene.net source code.
