### ISSUE TITLE
HPC: link to Bowtie doesn't work

### ISSUE THREAD

**Issue by EvelinaBiserova** [ugeneunipro/ugeneunipro.github.io#6]
Section "UGENE Genome Aligner"
[ugeneunipro.github.io/hpc.html](https://ugeneunipro.github.io/hpc.html) -- doesn't work
[ugene.net/hpc.html](http://ugene.net/hpc.html) -- work

**Comment by yalgaer** [comment]
It should work now, could you please re-check

**Comment by EvelinaBiserova** [comment]
Please replace the link `https://bowtie-bio.sourceforge.net/index.shtml` with `http://bowtie-bio.sourceforge.net/index.shtml` (https->http)

**Comment by EvelinaBiserova** [comment]
- [ ] [hpc.html](https://github.com/ugeneunipro/ugeneunipro.github.io/edit/gh-pages/docs/hpc.html), line 52, change `https`->`http` like in [master](https://github.com/ugeneunipro/ugeneunipro.github.io/blob/938b9d4f151fe7d03d195d2fd8c26d73088a7090/docs/hpc.html#L52). Please
