### ISSUE TITLE
FAQ: nextversion link doesn't work

### ISSUE THREAD

**Issue by EvelinaBiserova** [ugeneunipro/ugeneunipro.github.io#9]
Link for features planned for the next release doesn't work
[ugeneunipro.github.io/faq.html#next_release](https://ugeneunipro.github.io/faq.html#next_release)
[ugene.net/faq.html#next_release](http://ugene.net/faq.html#next_release)

**Comment by yalgaer** [comment]
Good finding. We miss valid data under this link for > 1 year.
